version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - npetzall
    assignees:
      - npetzall
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - npetzall
    assignees:
      - npetzall
  - package-ecosystem: "pip"
    directory: "/.github/scripts/release-version"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - npetzall
    assignees:
      - npetzall
  - package-ecosystem: "pip"
    directory: "/.github/scripts/release-notes"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - npetzall
    assignees:
      - npetzall
  - package-ecosystem: "pip"
    directory: "/.github/scripts/pr-labels"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - npetzall
    assignees:
      - npetzall
  - package-ecosystem: "pip"
    directory: "/.github/scripts/test-summary"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - npetzall
    assignees:
      - npetzall
