[package]
name = "move_maker"
version = "0.1.0"
rust-version = "1.90.0"
edition = "2024"

[dependencies]
hcl-rs = "0.19.4"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"

[dev-dependencies]
tempfile = "3.10"
